# Generated by Django 4.0.5 on 2022-09-07 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100, null=True)),
                ('brief_description', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=30, null=True)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=30, null=True)),
                ('number_of_Products', models.CharField(max_length=30, null=True)),
                ('product_description', models.CharField(max_length=500, null=True)),
                ('product_image', models.ImageField(blank=True, default='Skincare.JPG', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ordered', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('Out of Stock', 'Out of Stock'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=30, null=True)),
                ('customer', models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
