# Generated by Django 4.0.5 on 2022-09-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skinhub', '0007_alter_item_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_image',
            field=models.ImageField(default='', upload_to='image/'),
        ),
    ]
