# Generated by Django 4.0.5 on 2022-09-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skinhub', '0008_alter_item_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
